friendica/docker

README.md, pwd.yml
Hi,
Some new stuff :-)
- Added a section "Running this image with docker-compose"
- Make the README.md better readable (input from https://github.com/docker-library/docs/pull/1234)
- Added a `pwd.yml` file for (later) usage ( https://labs.play-with-docker.com/ )
=> README.md enhancements & PWD preperation

.examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/app/Dockerfile, .examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/app/smtp-config.sh, .examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/db.env, .examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/docker-compose.yml, .examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/proxy/Dockerfile, .examples/docker-compose/with-traefik-proxy/mariadb-cron-smtp/apache/proxy/traefik.toml
As I said, I'd like to add some docker-compose examples for easy usage :-)
This is one of about 5-6 example-directories I want to add.
=> Docker-Compose examples

.bin/friendica, .config/htconfig.php, 2018.05-rc/apache/bin/friendica, 2018.05-rc/apache/config/htconfig.php, 2018.05-rc/fpm-alpine/bin/friendica, 2018.05-rc/fpm-alpine/config/htconfig.php, 2018.05-rc/fpm/bin/friendica, 2018.05-rc/fpm/config/htconfig.php
Fixed a `.bin/friendica` copy bug
Fixed the `.config/htconfig.php` for MariaDB use
=> Bugfix of htconfig.php and friendica script

.examples/README.md, README-MAINTENANCE.md, README.md
- Adding `.examples/README.md`
- Adding `README-MAINTENANCE.md`
- Updating `README.md`
Follow up #9
=> Adding READMEs

.bin/friendica, 2018.05-rc/apache/bin/friendica, 2018.05-rc/fpm-alpine/bin/friendica, 2018.05-rc/fpm/bin/friendica, README-MAINTENANCE.md, README.md
bugfixing for the console wrapper part of the friendica script
and added some new README text :-)
=> Bugfixing friendica script

.bin/friendica, 2018.05/apache/bin/friendica, 2018.05/fpm-alpine/bin/friendica, 2018.05/fpm/bin/friendica, 2018.08-dev/apache/bin/friendica, 2018.08-dev/fpm-alpine/bin/friendica, 2018.08-dev/fpm/bin/friendica
Update was not working for develop branch :-(
... I'm not able to test every step in every kind of installation.
Maybe when there are some other users/contributors, the number of bugs will hopefully fall.
=> Bugfixing friendica shell script

2018.09/apache/upgrade.exclude, 2018.09/fpm-alpine/upgrade.exclude, 2018.09/fpm/upgrade.exclude, 2018.12-dev/apache/upgrade.exclude, 2018.12-dev/fpm-alpine/upgrade.exclude, 2018.12-dev/fpm/upgrade.exclude, upgrade.exclude
Fixing #36 
We excluded **every** `home.*` 
=> so we excluded `mod/home.php` as well
Should be fixed now
=> excluding too much files

.travis.yml, 2018.12-rc/apache/Dockerfile, 2018.12-rc/apache/cron.sh, 2018.12-rc/apache/entrypoint.sh, 2018.12-rc/apache/upgrade.exclude, 2018.12-rc/fpm-alpine/Dockerfile, 2018.12-rc/fpm-alpine/cron.sh, 2018.12-rc/fpm-alpine/entrypoint.sh, 2018.12-rc/fpm-alpine/upgrade.exclude, 2018.12-rc/fpm/Dockerfile, 2018.12-rc/fpm/cron.sh, 2018.12-rc/fpm/entrypoint.sh, 2018.12-rc/fpm/upgrade.exclude, update.sh
Adding branch "2018.12-rc" to docker images
=> Adding friendica release 2018.12-rc

.travis.yml
=> Forgot bashbrew binary

.docker-files/upgrade.exclude, 2019.01/apache/upgrade.exclude, 2019.01/fpm-alpine/Dockerfile, 2019.01/fpm-alpine/upgrade.exclude, 2019.01/fpm/upgrade.exclude, 2019.03-dev/apache/upgrade.exclude, 2019.03-dev/fpm-alpine/Dockerfile, 2019.03-dev/fpm-alpine/upgrade.exclude, 2019.03-dev/fpm/upgrade.exclude, Dockerfile-alpine.template
Because I already deleted my whole `/storage/` directory during a image restart, I'm now excluding the whole directory ...
=> New storage directory to exclude

.docker-files/entrypoint.sh, 2019.01/apache/entrypoint.sh, 2019.01/fpm-alpine/entrypoint.sh, 2019.01/fpm/entrypoint.sh, 2019.03-dev/apache/entrypoint.sh, 2019.03-dev/fpm-alpine/entrypoint.sh, 2019.03-dev/fpm/entrypoint.sh, 2019.03-rc/apache/entrypoint.sh, 2019.03-rc/fpm-alpine/entrypoint.sh, 2019.03-rc/fpm/entrypoint.sh
=> Wrong usage of lowercase

.travis.yml, 2019.06-rc/apache/Dockerfile, 2019.06-rc/apache/cron.sh, 2019.06-rc/apache/entrypoint.sh, 2019.06-rc/apache/upgrade.exclude, 2019.06-rc/fpm-alpine/Dockerfile, 2019.06-rc/fpm-alpine/cron.sh, 2019.06-rc/fpm-alpine/entrypoint.sh, 2019.06-rc/fpm-alpine/upgrade.exclude, 2019.06-rc/fpm/Dockerfile, 2019.06-rc/fpm/cron.sh, 2019.06-rc/fpm/entrypoint.sh, 2019.06-rc/fpm/upgrade.exclude, update.sh
Welcome 2019.06-rc
Based on https://github.com/friendica/friendica/commit/05d3062595f81c5ce8d1abd1c2f0b421d5e2fcf7
=> Update to 2019.06-rc

.docker-files/entrypoint.sh, 2019.06/apache/entrypoint.sh, 2019.06/fpm-alpine/entrypoint.sh, 2019.06/fpm/entrypoint.sh, 2019.09-dev/apache/entrypoint.sh, 2019.09-dev/fpm-alpine/entrypoint.sh, 2019.09-dev/fpm/entrypoint.sh, README.md
=> Add possibility to overwrite git Repo&branch

.travis.yml, 2019.09-rc/apache/Dockerfile, 2019.09-rc/apache/config/00apcu.config.php, 2019.09-rc/apache/config/01redis.config.php, 2019.09-rc/apache/config/zz-docker.config.php, 2019.09-rc/apache/cron.sh, 2019.09-rc/apache/entrypoint.sh, 2019.09-rc/apache/upgrade.exclude, 2019.09-rc/fpm-alpine/Dockerfile, 2019.09-rc/fpm-alpine/config/00apcu.config.php, 2019.09-rc/fpm-alpine/config/01redis.config.php, 2019.09-rc/fpm-alpine/config/zz-docker.config.php, 2019.09-rc/fpm-alpine/cron.sh, 2019.09-rc/fpm-alpine/entrypoint.sh, 2019.09-rc/fpm-alpine/upgrade.exclude, 2019.09-rc/fpm/Dockerfile, 2019.09-rc/fpm/config/00apcu.config.php, 2019.09-rc/fpm/config/01redis.config.php, 2019.09-rc/fpm/config/zz-docker.config.php, 2019.09-rc/fpm/cron.sh, 2019.09-rc/fpm/entrypoint.sh, 2019.09-rc/fpm/upgrade.exclude, update.sh
=> Introduce 2019.09-rc

2019.09/apache/entrypoint.sh, 2019.09/fpm-alpine/entrypoint.sh, 2019.09/fpm/entrypoint.sh, 2019.12-dev/apache/entrypoint.sh, 2019.12-dev/fpm-alpine/entrypoint.sh, 2019.12-dev/fpm/entrypoint.sh, docker-entrypoint.sh
=> Checks if the branch and repository exists (avoid crash)

2019.09/apache/Dockerfile, 2019.09/fpm-alpine/Dockerfile, 2019.09/fpm/Dockerfile, 2019.12-dev/apache/Dockerfile, 2019.12-dev/fpm-alpine/Dockerfile, 2019.12-dev/fpm/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template
Fixes #83 
- Adding ldap support to the images
Using alpine dev-dependencies based on https://github.com/docker-library/php/issues/75#issuecomment-400284429
=> Add ldap support for ldapauth addon

2019.12/apache/cron.sh, 2019.12/apache/entrypoint.sh, 2019.12/fpm-alpine/Dockerfile, 2019.12/fpm-alpine/cron.sh, 2019.12/fpm-alpine/entrypoint.sh, 2019.12/fpm/cron.sh, 2019.12/fpm/entrypoint.sh, 2020.03-dev/apache/cron.sh, 2020.03-dev/apache/entrypoint.sh, 2020.03-dev/fpm-alpine/Dockerfile, 2020.03-dev/fpm-alpine/cron.sh, 2020.03-dev/fpm-alpine/entrypoint.sh, 2020.03-dev/fpm/cron.sh, 2020.03-dev/fpm/entrypoint.sh, Dockerfile-alpine.template, docker-cron.sh, docker-entrypoint.sh
None of these are pressing or show-stoppers (in the context of getting https://github.com/docker-library/official-images/pull/6446 merged), but they're all minor improvements/adjustments I noticed while reviewing.
=> Minor syntax/correctness tweaks

2019.12/apache/entrypoint.sh, 2019.12/fpm-alpine/entrypoint.sh, 2019.12/fpm/entrypoint.sh, 2020.03-dev/apache/entrypoint.sh, 2020.03-dev/fpm-alpine/entrypoint.sh, 2020.03-dev/fpm/entrypoint.sh, docker-entrypoint.sh
The develop version wasn't triggered to get rsyncd over the html-files. This is now fixed :)
=> Fix dev update

2019.12/apache/entrypoint.sh, 2019.12/fpm-alpine/entrypoint.sh, 2019.12/fpm/entrypoint.sh, 2020.03-dev/apache/entrypoint.sh, 2020.03-dev/fpm-alpine/entrypoint.sh, 2020.03-dev/fpm/entrypoint.sh, README.md, docker-entrypoint.sh
- Remove MYSQL_USERNAME and FRIENDICA_PHP_PATH environment variables
- remove --link usage in README (replace with --network some-network)
Changes based on the feedback from https://github.com/docker-library/docs/pull/1551
=> Some Improvements

.config/zz-docker.config.php, 2019.12/apache/config/zz-docker.config.php, 2019.12/fpm-alpine/config/zz-docker.config.php, 2019.12/fpm/config/zz-docker.config.php, 2020.03-dev/apache/config/zz-docker.config.php, 2020.03-dev/fpm-alpine/config/zz-docker.config.php, 2020.03-dev/fpm/config/zz-docker.config.php
=> Fix config-entry for admin_email

2019.12/apache/Dockerfile, 2019.12/apache/cron.sh, 2019.12/fpm-alpine/Dockerfile, 2019.12/fpm-alpine/cron.sh, 2019.12/fpm/Dockerfile, 2019.12/fpm/cron.sh, 2020.03-dev/apache/Dockerfile, 2020.03-dev/apache/cron.sh, 2020.03-dev/fpm-alpine/Dockerfile, 2020.03-dev/fpm-alpine/cron.sh, 2020.03-dev/fpm/Dockerfile, 2020.03-dev/fpm/cron.sh, docker-cron.sh
related to #105 
daemon.php is not managing its children but sh could do it.
=> keep /bin/sh as parent process

2020.07/apache/Dockerfile, 2020.07/apache/entrypoint.sh, 2020.07/fpm-alpine/Dockerfile, 2020.07/fpm-alpine/entrypoint.sh, 2020.07/fpm/Dockerfile, 2020.07/fpm/entrypoint.sh, 2020.09-dev/apache/Dockerfile, 2020.09-dev/apache/entrypoint.sh, 2020.09-dev/fpm-alpine/Dockerfile, 2020.09-dev/fpm-alpine/entrypoint.sh, 2020.09-dev/fpm/Dockerfile, 2020.09-dev/fpm/entrypoint.sh, Dockerfile-alpine.template, Dockerfile-debian.template, README.md, docker-entrypoint.sh
As suggested here https://github.com/docker-library/official-images/pull/8341#issuecomment-658308684 by @yosifkit , I now upgrade the Friendica debian images to buster.
=> Switch to Debian Buster

2020.07/apache/cron.sh, 2020.07/apache/entrypoint.sh, 2020.07/apache/setup_msmtp.sh, 2020.07/fpm-alpine/cron.sh, 2020.07/fpm-alpine/entrypoint.sh, 2020.07/fpm-alpine/setup_msmtp.sh, 2020.07/fpm/cron.sh, 2020.07/fpm/entrypoint.sh, 2020.07/fpm/setup_msmtp.sh, 2020.09-dev/apache/cron.sh, 2020.09-dev/apache/entrypoint.sh, 2020.09-dev/apache/setup_msmtp.sh, 2020.09-dev/fpm-alpine/cron.sh, 2020.09-dev/fpm-alpine/entrypoint.sh, 2020.09-dev/fpm-alpine/setup_msmtp.sh, 2020.09-dev/fpm/cron.sh, 2020.09-dev/fpm/entrypoint.sh, 2020.09-dev/fpm/setup_msmtp.sh, docker-cron.sh, docker-entrypoint.sh, docker-setup_msmtp.sh, update.sh
- Extract msmtp setup into own file
- use msmtp setup in cron and app container
- fix wrong SMTP Env variable
=> Use MSMTP settings in cron

.github/workflows/images.yml, .github/workflows/update-sh.yml
Now run update.sh on PR and on cron
=> Optimize Github Action Workflow
